extends SceneTree
## Writes the ONE placeholder icon the HUD loadout strip falls back to when
## a catalog row has no sprite of its own yet:
##   res://assets/icons/placeholder.png  (64x64, neutral tile with a border)
##
## Run it from the project root, then re-import so the .ctex sidecar exists:
##   godot --headless --path . -s res://scripts/tools/generate_placeholder_icon.gd
##   godot --headless --import
##
## Deliberately free of autoloads and of every class_name in this project:
## a `-s` SceneTree harness has NO autoloads instanced, so anything that
## reached RunState/SaveData/Sfx/Pools would abort before the first pixel.
## Sibling of generate_sfx.gd, same contract: deterministic, one asset,
## regenerated by hand and committed.

const OUTPUT_PATH: String = "res://assets/icons/placeholder.png"
const SIZE: int = 64
## Border thickness, and the inset of the diagonal "no art yet" hatch.
const BORDER: int = 3
const HATCH_STEP: int = 10

## Neutral slate that reads under every rarity border the slot draws around
## it, without competing with any of the four rarity colors.
const FILL: Color = Color(0.16, 0.17, 0.22, 1.0)
const BORDER_COLOR: Color = Color(0.42, 0.45, 0.54, 1.0)
const HATCH_COLOR: Color = Color(0.24, 0.26, 0.32, 1.0)


func _init() -> void:
	var image := Image.create_empty(SIZE, SIZE, false, Image.FORMAT_RGBA8)
	image.fill(FILL)
	# Diagonal hatch first, so the border draws over its ends.
	for y in SIZE:
		for x in SIZE:
			if (x + y) % HATCH_STEP == 0:
				image.set_pixel(x, y, HATCH_COLOR)
	for y in SIZE:
		for x in SIZE:
			if x < BORDER or y < BORDER or x >= SIZE - BORDER or y >= SIZE - BORDER:
				image.set_pixel(x, y, BORDER_COLOR)
	var directory := OUTPUT_PATH.get_base_dir()
	if not DirAccess.dir_exists_absolute(ProjectSettings.globalize_path(directory)):
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(directory))
	var error := image.save_png(OUTPUT_PATH)
	if error != OK:
		push_error("generate_placeholder_icon: save_png failed (%d)" % error)
	else:
		print("Placeholder icon written: %s" % OUTPUT_PATH)
	quit()
